; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=amdgcn--amdhsa -mcpu=gfx90a -verify-machineinstrs < %s | FileCheck -check-prefixes=NO-PRELOAD %s
; RUN: llc -mtriple=amdgcn--amdhsa -mcpu=gfx90a -amdgpu-kernarg-preload-count=1 < %s | FileCheck -check-prefixes=PRELOAD-1 %s
; RUN: llc -mtriple=amdgcn--amdhsa -mcpu=gfx90a -amdgpu-kernarg-preload-count=2 < %s | FileCheck -check-prefixes=PRELOAD-2 %s
; RUN: llc -mtriple=amdgcn--amdhsa -mcpu=gfx90a -amdgpu-kernarg-preload-count=4 < %s | FileCheck -check-prefixes=PRELOAD-4 %s
; RUN: llc -mtriple=amdgcn--amdhsa -mcpu=gfx90a -amdgpu-kernarg-preload-count=8 < %s | FileCheck -check-prefixes=PRELOAD-8 %s

define amdgpu_kernel void @ptr1_i16_preload_arg(ptr addrspace(1) %out, i16 %arg0) {
; NO-PRELOAD-LABEL: ptr1_i16_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dword s2, s[4:5], 0x8
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    s_and_b32 s2, s2, 0xffff
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s2
; NO-PRELOAD-NEXT:    global_store_dword v0, v1, s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: ptr1_i16_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB0_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB0_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    s_and_b32 s2, s2, 0xffff
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-1-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: ptr1_i16_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB0_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b32 s2, s8
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB0_2: ; Block address taken
; PRELOAD-2-NEXT:    s_and_b32 s2, 0xffff, s2
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-2-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: ptr1_i16_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB0_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b32 s2, s8
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB0_2: ; Block address taken
; PRELOAD-4-NEXT:    s_and_b32 s2, 0xffff, s2
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-4-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: ptr1_i16_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB0_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b32 s2, s8
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB0_2: ; Block address taken
; PRELOAD-8-NEXT:    s_and_b32 s2, 0xffff, s2
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-8-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  %ext = zext i16 %arg0 to i32
  store i32 %ext, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @ptr1_i32_preload_arg(ptr addrspace(1) %out, i32 %arg0) {
; NO-PRELOAD-LABEL: ptr1_i32_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dword s2, s[4:5], 0x8
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s2
; NO-PRELOAD-NEXT:    global_store_dword v0, v1, s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: ptr1_i32_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB1_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB1_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-1-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: ptr1_i32_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB1_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b32 s2, s8
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB1_2: ; Block address taken
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-2-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: ptr1_i32_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB1_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b32 s2, s8
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB1_2: ; Block address taken
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-4-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: ptr1_i32_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB1_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b32 s2, s8
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB1_2: ; Block address taken
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-8-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store i32 %arg0, ptr addrspace(1) %out
  ret void
}


define amdgpu_kernel void @i32_ptr1_i32_preload_arg(i32 %arg0, ptr addrspace(1) %out, i32 %arg1) {
; NO-PRELOAD-LABEL: i32_ptr1_i32_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dword s2, s[4:5], 0x10
; NO-PRELOAD-NEXT:    s_load_dword s3, s[4:5], 0x0
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x8
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    s_add_i32 s2, s3, s2
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s2
; NO-PRELOAD-NEXT:    global_store_dword v0, v1, s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: i32_ptr1_i32_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dword s0, s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB2_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b32 s0, s6
; PRELOAD-1-NEXT:  .LBB2_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dword s1, s[4:5], 0x10
; PRELOAD-1-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    s_add_i32 s0, s0, s1
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s0
; PRELOAD-1-NEXT:    global_store_dword v0, v1, s[2:3]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: i32_ptr1_i32_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x8
; PRELOAD-2-NEXT:    s_load_dword s2, s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB2_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b32 s2, s6
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[8:9]
; PRELOAD-2-NEXT:  .LBB2_2: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dword s3, s[4:5], 0x10
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-2-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-2-NEXT:    s_add_i32 s2, s2, s3
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-2-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: i32_ptr1_i32_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dword s2, s[4:5], 0x10
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x8
; PRELOAD-4-NEXT:    s_load_dword s3, s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB2_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b32 s2, s10
; PRELOAD-4-NEXT:    s_mov_b32 s3, s6
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[8:9]
; PRELOAD-4-NEXT:  .LBB2_2: ; Block address taken
; PRELOAD-4-NEXT:    s_add_i32 s2, s3, s2
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-4-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: i32_ptr1_i32_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dword s2, s[4:5], 0x10
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x8
; PRELOAD-8-NEXT:    s_load_dword s3, s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB2_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b32 s2, s10
; PRELOAD-8-NEXT:    s_mov_b32 s3, s6
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[8:9]
; PRELOAD-8-NEXT:  .LBB2_2: ; Block address taken
; PRELOAD-8-NEXT:    s_add_i32 s2, s3, s2
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-8-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  %add = add i32 %arg0, %arg1
  store i32 %add, ptr addrspace(1) %out
  ret void
}

define amdgpu_kernel void @ptr1_i16_i16_preload_arg(ptr addrspace(1) %out, i16 %arg0, i16 %arg1) {
; NO-PRELOAD-LABEL: ptr1_i16_i16_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dword s2, s[4:5], 0x8
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    s_lshr_b32 s3, s2, 16
; NO-PRELOAD-NEXT:    s_and_b32 s2, s2, 0xffff
; NO-PRELOAD-NEXT:    s_add_i32 s2, s2, s3
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s2
; NO-PRELOAD-NEXT:    global_store_dword v0, v1, s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: ptr1_i16_i16_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB3_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB3_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    s_lshr_b32 s3, s2, 16
; PRELOAD-1-NEXT:    s_and_b32 s2, s2, 0xffff
; PRELOAD-1-NEXT:    s_add_i32 s2, s2, s3
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-1-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: ptr1_i16_i16_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_load_dword s3, s[4:5], 0x8
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_mov_b32 s2, s3
; PRELOAD-2-NEXT:    s_branch .LBB3_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b32 s2, s8
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB3_2: ; Block address taken
; PRELOAD-2-NEXT:    s_lshr_b32 s3, s3, 16
; PRELOAD-2-NEXT:    s_and_b32 s2, 0xffff, s2
; PRELOAD-2-NEXT:    s_add_i32 s2, s2, s3
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-2-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: ptr1_i16_i16_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_lshr_b32 s3, s2, 16
; PRELOAD-4-NEXT:    s_branch .LBB3_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b32 s2, s8
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:    s_lshr_b32 s3, s8, 16
; PRELOAD-4-NEXT:  .LBB3_2: ; Block address taken
; PRELOAD-4-NEXT:    s_and_b32 s2, 0xffff, s2
; PRELOAD-4-NEXT:    s_and_b32 s3, 0xffff, s3
; PRELOAD-4-NEXT:    s_add_i32 s2, s2, s3
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-4-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: ptr1_i16_i16_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dword s2, s[4:5], 0x8
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_lshr_b32 s3, s2, 16
; PRELOAD-8-NEXT:    s_branch .LBB3_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b32 s2, s8
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:    s_lshr_b32 s3, s8, 16
; PRELOAD-8-NEXT:  .LBB3_2: ; Block address taken
; PRELOAD-8-NEXT:    s_and_b32 s2, 0xffff, s2
; PRELOAD-8-NEXT:    s_and_b32 s3, 0xffff, s3
; PRELOAD-8-NEXT:    s_add_i32 s2, s2, s3
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-8-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  %ext = zext i16 %arg0 to i32
  %ext1 = zext i16 %arg1 to i32
  %add = add i32 %ext, %ext1
  store i32 %add, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @byref_preload_arg(ptr addrspace(1) %out, ptr addrspace(4) byref(i32) align(256) %in.byref, i32 %after.offset) {
; NO-PRELOAD-LABEL: byref_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x100
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s1
; NO-PRELOAD-NEXT:    global_store_dword v0, v1, s[2:3]
; NO-PRELOAD-NEXT:    s_waitcnt vmcnt(0)
; NO-PRELOAD-NEXT:    global_store_dword v0, v2, s[2:3]
; NO-PRELOAD-NEXT:    s_waitcnt vmcnt(0)
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: byref_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB4_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB4_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x100
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s3
; PRELOAD-1-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-1-NEXT:    global_store_dword v0, v2, s[0:1]
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: byref_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB4_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB4_2: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x100
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-2-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, s3
; PRELOAD-2-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-2-NEXT:    global_store_dword v0, v2, s[0:1]
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: byref_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB4_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB4_2: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x100
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-4-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, s3
; PRELOAD-4-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-4-NEXT:    global_store_dword v0, v2, s[0:1]
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: byref_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB4_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB4_2: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x100
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-8-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, s3
; PRELOAD-8-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-8-NEXT:    global_store_dword v0, v2, s[0:1]
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0)
; PRELOAD-8-NEXT:    s_endpgm
  %in = load i32, ptr addrspace(4) %in.byref
  store volatile i32 %in, ptr addrspace(1) %out, align 4
  store volatile i32 %after.offset, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @v8i32_arg(ptr addrspace(1) nocapture %out, <8 x i32> %in) nounwind {
; NO-PRELOAD-LABEL: v8i32_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx8 s[8:15], s[4:5], 0x20
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v4, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s12
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s13
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s14
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v3, s15
; NO-PRELOAD-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; NO-PRELOAD-NEXT:    s_nop 0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s8
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s9
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s10
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v3, s11
; NO-PRELOAD-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: v8i32_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB5_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB5_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx8 s[4:11], s[4:5], 0x20
; PRELOAD-1-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-1-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-1-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, s4
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s5
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s6
; PRELOAD-1-NEXT:    v_mov_b32_e32 v3, s7
; PRELOAD-1-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: v8i32_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB5_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB5_2: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx8 s[4:11], s[4:5], 0x20
; PRELOAD-2-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-2-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-2-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-2-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, s4
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s5
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, s6
; PRELOAD-2-NEXT:    v_mov_b32_e32 v3, s7
; PRELOAD-2-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: v8i32_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB5_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB5_2: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx8 s[4:11], s[4:5], 0x20
; PRELOAD-4-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-4-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-4-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-4-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, s4
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s5
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, s6
; PRELOAD-4-NEXT:    v_mov_b32_e32 v3, s7
; PRELOAD-4-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: v8i32_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB5_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB5_2: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx8 s[4:11], s[4:5], 0x20
; PRELOAD-8-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-8-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-8-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-8-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, s4
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s5
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, s6
; PRELOAD-8-NEXT:    v_mov_b32_e32 v3, s7
; PRELOAD-8-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store <8 x i32> %in, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @v3i16_preload_arg(ptr addrspace(1) nocapture %out, <3 x i16> %in) nounwind {
; NO-PRELOAD-LABEL: v3i16_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s3
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s2
; NO-PRELOAD-NEXT:    global_store_short v0, v1, s[0:1] offset:4
; NO-PRELOAD-NEXT:    global_store_dword v0, v2, s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: v3i16_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB6_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB6_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s3
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s2
; PRELOAD-1-NEXT:    global_store_short v0, v1, s[0:1] offset:4
; PRELOAD-1-NEXT:    global_store_dword v0, v2, s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: v3i16_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB6_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB6_2: ; Block address taken
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s3
; PRELOAD-2-NEXT:    global_store_short v0, v1, s[0:1] offset:4
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-2-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: v3i16_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB6_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB6_2: ; Block address taken
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s3
; PRELOAD-4-NEXT:    global_store_short v0, v1, s[0:1] offset:4
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-4-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: v3i16_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB6_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB6_2: ; Block address taken
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s3
; PRELOAD-8-NEXT:    global_store_short v0, v1, s[0:1] offset:4
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s2
; PRELOAD-8-NEXT:    global_store_dword v0, v1, s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store <3 x i16> %in, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @v3i32_preload_arg(ptr addrspace(1) nocapture %out, <3 x i32> %in) nounwind {
; NO-PRELOAD-LABEL: v3i32_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x10
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[6:7], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v3, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s1
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s2
; NO-PRELOAD-NEXT:    global_store_dwordx3 v3, v[0:2], s[6:7]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: v3i32_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB7_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB7_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx4 s[4:7], s[4:5], 0x10
; PRELOAD-1-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, s4
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s5
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s6
; PRELOAD-1-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: v3i32_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx4 s[16:19], s[4:5], 0x10
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB7_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b32 s18, s12
; PRELOAD-2-NEXT:    s_mov_b32 s17, s11
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:    s_mov_b32 s16, s10
; PRELOAD-2-NEXT:  .LBB7_2: ; Block address taken
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, s16
; PRELOAD-2-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s17
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, s18
; PRELOAD-2-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: v3i32_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx4 s[16:19], s[4:5], 0x10
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB7_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b32 s18, s12
; PRELOAD-4-NEXT:    s_mov_b32 s17, s11
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:    s_mov_b32 s16, s10
; PRELOAD-4-NEXT:  .LBB7_2: ; Block address taken
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, s16
; PRELOAD-4-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s17
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, s18
; PRELOAD-4-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: v3i32_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx4 s[16:19], s[4:5], 0x10
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB7_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b32 s18, s12
; PRELOAD-8-NEXT:    s_mov_b32 s17, s11
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:    s_mov_b32 s16, s10
; PRELOAD-8-NEXT:  .LBB7_2: ; Block address taken
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, s16
; PRELOAD-8-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s17
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, s18
; PRELOAD-8-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store <3 x i32> %in, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @v3f32_preload_arg(ptr addrspace(1) nocapture %out, <3 x float> %in) nounwind {
; NO-PRELOAD-LABEL: v3f32_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x10
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[6:7], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v3, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s1
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s2
; NO-PRELOAD-NEXT:    global_store_dwordx3 v3, v[0:2], s[6:7]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: v3f32_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB8_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB8_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx4 s[4:7], s[4:5], 0x10
; PRELOAD-1-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, s4
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s5
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s6
; PRELOAD-1-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: v3f32_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx4 s[16:19], s[4:5], 0x10
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB8_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b32 s18, s12
; PRELOAD-2-NEXT:    s_mov_b32 s17, s11
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:    s_mov_b32 s16, s10
; PRELOAD-2-NEXT:  .LBB8_2: ; Block address taken
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, s16
; PRELOAD-2-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s17
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, s18
; PRELOAD-2-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: v3f32_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx4 s[16:19], s[4:5], 0x10
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB8_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b32 s18, s12
; PRELOAD-4-NEXT:    s_mov_b32 s17, s11
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:    s_mov_b32 s16, s10
; PRELOAD-4-NEXT:  .LBB8_2: ; Block address taken
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, s16
; PRELOAD-4-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s17
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, s18
; PRELOAD-4-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: v3f32_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx4 s[16:19], s[4:5], 0x10
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB8_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b32 s18, s12
; PRELOAD-8-NEXT:    s_mov_b32 s17, s11
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:    s_mov_b32 s16, s10
; PRELOAD-8-NEXT:  .LBB8_2: ; Block address taken
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, s16
; PRELOAD-8-NEXT:    v_mov_b32_e32 v3, 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s17
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, s18
; PRELOAD-8-NEXT:    global_store_dwordx3 v3, v[0:2], s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store <3 x float> %in, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_kernel void @v5f64_arg(ptr addrspace(1) nocapture %out, <5 x double> %in) nounwind {
; NO-PRELOAD-LABEL: v5f64_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x60
; NO-PRELOAD-NEXT:    s_load_dwordx8 s[8:15], s[4:5], 0x40
; NO-PRELOAD-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v4, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_pk_mov_b32 v[2:3], s[0:1], s[0:1] op_sel:[0,1]
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s12
; NO-PRELOAD-NEXT:    global_store_dwordx2 v4, v[2:3], s[2:3] offset:32
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s13
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s14
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v3, s15
; NO-PRELOAD-NEXT:    global_store_dwordx4 v4, v[0:3], s[2:3] offset:16
; NO-PRELOAD-NEXT:    s_nop 0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s8
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s9
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, s10
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v3, s11
; NO-PRELOAD-NEXT:    global_store_dwordx4 v4, v[0:3], s[2:3]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: v5f64_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB9_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB9_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x60
; PRELOAD-1-NEXT:    s_load_dwordx8 s[8:15], s[4:5], 0x40
; PRELOAD-1-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_pk_mov_b32 v[2:3], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, s12
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s13
; PRELOAD-1-NEXT:    global_store_dwordx2 v4, v[2:3], s[0:1] offset:32
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s14
; PRELOAD-1-NEXT:    v_mov_b32_e32 v3, s15
; PRELOAD-1-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-1-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-1-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: v5f64_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB9_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB9_2: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x60
; PRELOAD-2-NEXT:    s_load_dwordx8 s[8:15], s[4:5], 0x40
; PRELOAD-2-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-2-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-2-NEXT:    v_pk_mov_b32 v[2:3], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, s12
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s13
; PRELOAD-2-NEXT:    global_store_dwordx2 v4, v[2:3], s[0:1] offset:32
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, s14
; PRELOAD-2-NEXT:    v_mov_b32_e32 v3, s15
; PRELOAD-2-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-2-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-2-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-2-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: v5f64_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB9_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB9_2: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x60
; PRELOAD-4-NEXT:    s_load_dwordx8 s[8:15], s[4:5], 0x40
; PRELOAD-4-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-4-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-4-NEXT:    v_pk_mov_b32 v[2:3], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, s12
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s13
; PRELOAD-4-NEXT:    global_store_dwordx2 v4, v[2:3], s[0:1] offset:32
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, s14
; PRELOAD-4-NEXT:    v_mov_b32_e32 v3, s15
; PRELOAD-4-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-4-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-4-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-4-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: v5f64_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB9_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB9_2: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x60
; PRELOAD-8-NEXT:    s_load_dwordx8 s[8:15], s[4:5], 0x40
; PRELOAD-8-NEXT:    v_mov_b32_e32 v4, 0
; PRELOAD-8-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-8-NEXT:    v_pk_mov_b32 v[2:3], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, s12
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s13
; PRELOAD-8-NEXT:    global_store_dwordx2 v4, v[2:3], s[0:1] offset:32
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, s14
; PRELOAD-8-NEXT:    v_mov_b32_e32 v3, s15
; PRELOAD-8-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1] offset:16
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    v_mov_b32_e32 v0, s8
; PRELOAD-8-NEXT:    v_mov_b32_e32 v1, s9
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, s10
; PRELOAD-8-NEXT:    v_mov_b32_e32 v3, s11
; PRELOAD-8-NEXT:    global_store_dwordx4 v4, v[0:3], s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store <5 x double> %in, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @i64_kernel_preload_arg(ptr addrspace(1) %out, i64 %a) {
; NO-PRELOAD-LABEL: i64_kernel_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s2
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s3
; NO-PRELOAD-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: i64_kernel_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB10_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB10_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-1-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: i64_kernel_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB10_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB10_2: ; Block address taken
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-2-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-2-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: i64_kernel_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB10_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB10_2: ; Block address taken
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-4-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-4-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: i64_kernel_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB10_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB10_2: ; Block address taken
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-8-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-8-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store i64 %a, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @f64_kernel_preload_arg(ptr addrspace(1) %out, double %in) {
; NO-PRELOAD-LABEL: f64_kernel_preload_arg:
; NO-PRELOAD:       ; %bb.0:
; NO-PRELOAD-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v2, 0
; NO-PRELOAD-NEXT:    s_waitcnt lgkmcnt(0)
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v0, s2
; NO-PRELOAD-NEXT:    v_mov_b32_e32 v1, s3
; NO-PRELOAD-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; NO-PRELOAD-NEXT:    s_endpgm
;
; PRELOAD-1-LABEL: f64_kernel_preload_arg:
; PRELOAD-1:       ; %bb.0: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; PRELOAD-1-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-1-NEXT:    s_branch .LBB11_2
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:    s_nop 0
; PRELOAD-1-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-1-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-1-NEXT:  .LBB11_2: ; Block address taken
; PRELOAD-1-NEXT:    s_load_dwordx2 s[2:3], s[4:5], 0x8
; PRELOAD-1-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-1-NEXT:    s_waitcnt lgkmcnt(0)
; PRELOAD-1-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-1-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-1-NEXT:    s_endpgm
;
; PRELOAD-2-LABEL: f64_kernel_preload_arg:
; PRELOAD-2:       ; %bb.0: ; Block address taken
; PRELOAD-2-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-2-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-2-NEXT:    s_branch .LBB11_2
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:    s_nop 0
; PRELOAD-2-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-2-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-2-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-2-NEXT:  .LBB11_2: ; Block address taken
; PRELOAD-2-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-2-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-2-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-2-NEXT:    s_endpgm
;
; PRELOAD-4-LABEL: f64_kernel_preload_arg:
; PRELOAD-4:       ; %bb.0: ; Block address taken
; PRELOAD-4-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-4-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-4-NEXT:    s_branch .LBB11_2
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:    s_nop 0
; PRELOAD-4-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-4-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-4-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-4-NEXT:  .LBB11_2: ; Block address taken
; PRELOAD-4-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-4-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-4-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-4-NEXT:    s_endpgm
;
; PRELOAD-8-LABEL: f64_kernel_preload_arg:
; PRELOAD-8:       ; %bb.0: ; Block address taken
; PRELOAD-8-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x0
; PRELOAD-8-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRELOAD-8-NEXT:    s_branch .LBB11_2
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:    s_nop 0
; PRELOAD-8-NEXT:  ; %bb.1: ; Block address taken
; PRELOAD-8-NEXT:    s_mov_b64 s[2:3], s[8:9]
; PRELOAD-8-NEXT:    s_mov_b64 s[0:1], s[6:7]
; PRELOAD-8-NEXT:  .LBB11_2: ; Block address taken
; PRELOAD-8-NEXT:    v_mov_b32_e32 v2, 0
; PRELOAD-8-NEXT:    v_pk_mov_b32 v[0:1], s[2:3], s[2:3] op_sel:[0,1]
; PRELOAD-8-NEXT:    global_store_dwordx2 v2, v[0:1], s[0:1]
; PRELOAD-8-NEXT:    s_endpgm
  store double %in, ptr addrspace(1) %out
  ret void
}
